config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  root to: 'welcome#index'

  resources :patterns do
    resources :yarns
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  has_many :yarns, dependent: :destroy
  belongs_to :user
  validates :name, :photo_url, :designer_name, :details_body, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :patterns
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yarn.rb
class Yarn < ActiveRecord::Base
  belongs_to :pattern
  belongs_to :user
  validates :name, :yarn_url, :yards, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  

  def index
    @patterns = Pattern.all
  end

  def show
    @pattern = Pattern.find(params[:id])
    @yarn = @pattern.yarns.build
  end

  def new
    @pattern = Pattern.new
  end

  def edit
    @pattern = Pattern.find(params[:id])
    if @pattern.user == current_user
      @pattern
    else
      flash[:alert] = "Only the author of the pattern can edit"
      redirect_to patterns_path
    end
  end

  def create
    @pattern = Pattern.create!(pattern_params.merge(user: current_user))
     redirect_to pattern_path(@pattern)
  end

  def update
    @pattern = Pattern.find(params[:id])
      @pattern.update(pattern_params)
      redirect_to pattern_path(@pattern)
  end

def destroy
  @pattern = Pattern.find(params[:id])
   if @pattern.user == current_user
     @pattern.destroy
   else
     flash[:alert] = "Only the author of the pattern can delete"
   end

  redirect_to patterns_path
end

private
  def pattern_params
    params.require(:pattern).permit(:name, :photo_url, :designer_name, :details_body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController

  def create
    @pattern = Pattern.find(params[:pattern_id])
    @yarn = @pattern.yarns.create(yarn_params)

    if @yarn.save
      redirect_to pattern_path(@pattern)
    else
      render 'new'
    end
  end

  def edit
      @pattern = Pattern.find(params[:pattern_id])
      @yarn = @yarn.pattern
    end

    def update
      @pattern = Pattern.find(params[:pattern_id])
      @yarn = Yarn.find(params[:id])
      if @yarn.update(yarn_params)
        flash[:notice] = "Yarn was successfully updated."
        redirect_to @pattern
      else
        render :edit
      end
    end

    def destroy
      @yarn = Yarn.find(params[:id])
      @yarn.destroy
      redirect_to @yarn.pattern
    end

  private
    def yarn_params
      params.require(:yarn).permit(:name, :yarn_url, :yards)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>PatternOnPatternOff</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bubbler+One" rel="stylesheet">
  </head>
  <nav class="nav_bar">
    <h1 class="app_heading"><%= link_to 'Pattern On Pattern Off', root_path %></h1>
    <p class="nav_text"><%= link_to 'HOME', root_path %></p>
    <p class="nav_text"><%= link_to 'CROCHET PATTERNS', patterns_path %></p>
  </nav>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="user"><% if !current_user %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
      <% else %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <%= current_user.email %></div>
      <% end %>
    <%= yield %>

  </body>

</html>

app/views/patterns/edit.html.erb
<div class="heading">
<h1>Edit Pattern</h1>
</div>

<div class="edit_form">
<%= form_for @pattern do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :designer%>
  <%= f.text_field :designer_name %>

  <%= f.label :details %>
  <%= f.text_field :details_body %>

  <%= f.submit class: "update" %>
<% end %>

<%= form_for @pattern, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>
</div>

app/views/patterns/index.html.erb
<p><%= link_to 'New Pattern', new_pattern_path %></p>
<div class="heading">
<h1>Patterns</h1>
</div>
<div class="index_container">

  <% @patterns.each do |pattern| %>
  <div>
    <a href="/patterns/<%= pattern.id %>">
      <img class="index_img" src="<%= pattern.photo_url %>"/>
      <h4><%= pattern.name %></h4>
    </a>
      </div>
  <% end %>

</div>

app/views/patterns/new.html.erb
<div class="heading">
<h1>New Pattern</h1>
</div>

<div class="new_form">
<%= form_for @pattern do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :designer %>
  <%= f.text_field :designer_name %>

  <%= f.label :details %>
  <%= f.text_field :details_body %>

  <%= f.submit class: "update" %>
<% end %>
</div>

app/views/patterns/show.html.erb
<p><%= link_to 'New Pattern', new_pattern_path %> | <%= link_to "Edit Pattern", edit_pattern_path(@pattern) %></p>

  <div class="heading">
  <h2><%= @pattern.name %></h2>
  </div>
<div class="show_container">
  <div class="show_pattern">
    <div>
    <h4 class="designer"><%= link_to @pattern.designer_name, src='https://www.etsy.com/shop/Mbhfy'%> </h4>
    </div>
    <div class="show_box">
    <%= image_tag @pattern.photo_url, class: "pattern-photo" %>
    </div>
    <div class="show_body">
    <h4><%= @pattern.details_body %></h4>
    <div><p class="show_border"></p></div>
  </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Pattern On Pattern Off</h1>
<div class="welcome_text">
  POPO is an application that allows crochet lovers to view
  and read about garments and blankets designed by Mbhfy.com.
  Crochet lovers can also purchase the featured crochet patterns from
  Mbhfy's Etsy shop. Lovers can sign-up for an account and share their crochet patterns.

</div>

app/views/yarns/edit.html.erb
<h2>Edit Yarn</h2>

<%= form_for([@pattern, @pattern.yarns.build]) do |f| %>
  <p>
    <%= f.text_field :yarn_url %>
    <%= f.label :yarn_url %><br>
  </p>
  <p>
    <%= f.text_field :name %>
    <%= f.label :name %><br>
  </p>
  <p>
    <%= f.text_field :yards %>
    <%= f.label :yards %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <%= link_to 'Edit', edit_pattern_yarn_path(@pattern) %>

app/views/yarns/index.html.erb
<h1>Yarns</h1>
<% @yarns.each do |yarn| %>
  <div><%= link_to yarn.name, pattern_yarn_path(yarn) %> - <%= yarn.pattern.name %></div>
<% end %>

app/views/yarns/new.html.erb
<h2>New Yarn</h2>
<h1><%= @yarn.name %></h1>
<h2><%= @yarn.pattern.name %></h2>
<div>
  <%= image_tag @yarn.yarn_url %>
</div>

app/views/yarns/show.html.erb
<h1><%= @yarn.name %></h1>
<h2><%= @yarn.pattern.name %></h2>
<<<<<<< HEAD
<div>
=======

>>>>>>> 4eb97ab2520856b32bcee881950ea12f1d04eb6a
  <%= image_tag @yarn.yarn_url %>
</div>